name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies gmime
      run: sudo apt-get install libgmime-2.6-dev libmhash-dev libssl1.0-dev  libevent-dev libzdb-dev

    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    
